name: Build & Push Docker image to GHCR

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch            # ghcr.io/owner/repo:main
            type=semver,pattern={{version}}  # ghcr.io/owner/repo:1.2.3
            type=sha                         # ghcr.io/owner/repo:sha-<commit>

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: ./pok3mon
          file: ./pok3mon/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max